[mysqldb]
host = "127.0.0.1"
user = "root"
port = 3306
database = "starwarsDB"
password = "Root11"

[swapi]
home_url = "https://swapi.dev"
chracters = "/api/people"
films = "/api/films"
vehicle = "/api/vehicles"
starship = "/api/starships"
film = "/api/films"